#pragma config(Motor,  mtr_S1_C1_1,     ,              tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     ,              tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "MotorControl.c"
#include "ServoControl.c"

bool divide = false;

bool openGates = false;

bool rotateDown = true;

int ballCollect = 0;

void checkButtons(int button) {
  switch (button) {
  case 1: //LB
    if (openGates) {
      setServoPosition(servo1,140);
      setServoPosition(servo2,0);
    } else {
      setServoPosition(servo1, 0);
      setServoPosition(servo2,140);
    }
    openGates = !openGates;
  case 2: //RB
    if (rotateDown) {
      setServoPosition(servo3, 15);
    } else {
      setServoPosition(servo3,150);
    }
    rotateDown = !rotateDown;
    break;
  case 7: //LT
    lift(10,-10);
    break;
  case 8: //RT
    lift(-10,10);
    break;
  default:
    lift(0,0);
  }
}

void buttons() {
  if (joy1Btn(1) == 1) {
    switch (ballCollect) {
      case 0:
        motor[motorF] = 0;
        break;
      case 1:
        motor[motorF] = -30;
        break;
      case 2:
        motor[motorF] = 30;
        break;
    }
    ballCollect += (ballCollect != 2) ? 1 : -2;
  }
  else if (joy1Btn(2) == 1) { //A
    divide = !divide;
  }
  else if (joy1Btn(7) == 1) { //LT
    lift(25,-25);
  }
  else if (joy1Btn(8) == 1) {//RT
    lift(-25,25);
  }
  else if (joy1Btn(5) == 1) { //LB
    if (openGates) {
      setServoPosition(servo1,140);
      setServoPosition(servo2,0);
    } else {
      setServoPosition(servo1, 0);
      setServoPosition(servo2,140);
    }
    openGates = !openGates;
  }
  else if (joy1Btn(6) == 1) { //RB
    if (rotateDown) {
      setServoPosition(servo3, 15);
    } else {
      setServoPosition(servo3,150);
    }
    rotateDown = !rotateDown;
  }
  if (joy1Btn(7) != 1 && joy1Btn(8) != 1) {
    lift(0,0);
  }
}

void checkJoystick() {

   	  getJoystickSettings(joystick);

   	  drive(-joystick.joy1_y1/(divide ? 5 : 1), joystick.joy1_y2/(divide ? 5 : 1));

   	  /*int i;
   	  for (i = 0; i < 13; i++)
   	    if (joy1Btn(i) == 1) {
   	      checkButtons(i);
   	      return;
   	    }
   	  }
      checkButtons(-1);*/
      buttons();

      wait1Msec(200);

}

task main() {
  waitForStart();
  synchMotors(motorH, motorI);
  setServoPosition(servo1,140);
  setServoPosition(servo2,0);
  while (true) {
    nxtDisplayTextLine(0, "gates: %d", openGates);
    nxtDisplayTextLine(1, "divide: %d", divide);
    nxtDisplayTextLine(2, "rotate: %d", rotateDown);
    checkJoystick();
  }
}
